### ISSUE TITLE
Archive the cash basis tax journal

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#62]
Please archive the Cash basis tax journal that is created on installation of a new database. We will not use cash basis accounting, but if there is a customer who wants to use it, it can be un-archived manually.

![image](https://github.com/onesteinbv/addons-container/assets/30256071/796da2c5-471c-4ab5-b5e5-a12cb86f636b)

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/d6553fedc975e4024b647288a96bbaef218e0b4b

**Comment by ThijsvOers** [comment]
@astirpe I just created a new DB on Curq and I still see the tasx basis journal, it looks like it isn't archived

**Comment by astirpe** [comment]
Done in https://github.com/onesteinbv/addons-container/commit/48c8893e16cd92be60fb12f04345ec513291c596, this time should be ok

**Comment by ThijsvOers** [comment]
Tested with new Curq instance and ok
